Skip cert verification
davidmytton/url-verifier pull request #10
Opened 2024-09-26 15:36 UTC by skyheis

In some cases, we need to verify the url even if the HTTPS certificate is not valid.
This change gives the opportunity to skip the certificate validation.

2024-09-26 19:03 UTC, davidmytton requested changes
Thanks @skyheis. A test is failing, but I don't think it's related to your PR - just the status code has changed.

Either way, can you add a test for your changes please? You could fix the broken test as part of that (perhaps changing to a URL that 404s).

2024-09-26 20:48 UTC, skyheis commented
Yes, no problem! I will try to add the test and fix the broken one tomorrow. If not, I will as soon as I can 😁

2024-09-30 08:42 UTC, skyheis commented
I added the tests. About the test that failed (page not found), I didn't found any issue. It worked fine in my environment, even using Codespace works fine!

2024-09-30 12:57 UTC, davidmytton approved these changes
Thanks. Must've been a temporary issue with the other test!

2024-09-30 12:59 UTC, davidmytton requested changes
Looks like the tests are failing.

2024-10-17 13:34 UTC, skyheis commented
Hi David, I just update the tests, sorry for being late!
I had issue with the right error string because the firewall was filtering the request, it should work now.

2024-10-19 07:30 UTC, davidmytton approved these changes
Great, thanks!

2024-10-19 07:30 UTC, merged